# Generated by Django 3.1.7 on 2021-05-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
            ],
        ),
    ]
